### ISSUE TITLE
Sourcefile 'miRNA_genomic_position.csv' not accessable

### ISSUE THREAD

**Issue by DanielAmsel** [microPIECE-team/microPIECE#117]
# What did you do?
*Please explain what you did to encounter the problem.*
Running the test call
# Expected behavior
*Please explain the behavior you would expect.*
smooth run through
# Actual behavior
*Please describe the actual behavior.*
`Sourcefile 'miRNA_genomic_position.csv' not accessable`
# What version of \[Perl and microPIECE | Docker image and Docker\] are you using? 
*Did you use a local installation ? Then please tell us your Perl and microPIECE version.*
v.1.2.3
*Did you use a Docker image and Docker? Then please tell us your image and Docker version.*
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

# What operating system are you using?
*In any case, please tell us what OS you are using.*
Ubuntu 16.04.4 LTS

**Comment by greatfireball** [comment]
The bug is verified and solved
