### ISSUE TITLE
Update numbers for target prediction

### ISSUE THREAD

**Issue by greatfireball** [microPIECE-team/microPIECE#172]
Please update the numbers in our `paper.md` to reflect the new development.

- [x] Number of known microRNAs for *Tribolium castaneum*
- [x] Number of predicted target interactions with CLIP
- [x] Number of predicted target interactions without CLIP

The line concerning those numbers is https://github.com/microPIECE-team/microPIECE/blob/d16eb6fb2b93a0059d97b625dba51e167fa6d4ba/paper/paper.md#L48

**Comment by DanielAmsel** [comment]
Number of known microRNAs for TCA : 590
Number of known cDNA from ensembl in TCA : 18.534
Number of predicted miRNA target interactions without CLIP : 2.948.255

**Comment by DanielAmsel** [comment]
Number of predicted miRNA target interactions with (1of6 libs) CLIP : 17692 

* changed library support level from 3of6 to 1of6 
* added miRBase version (v22) to text
