### ISSUE TITLE
TopHat should be replaces by HiSAT2

### ISSUE THREAD

**Issue by greatfireball** [microPIECE-team/microPIECE#37]
http://ccb.jhu.edu/software/tophat/index.shtml and http://ccb.jhu.edu/software/hisat2

**Comment by greatfireball** [comment]
did you include `HiSat2`?

**Comment by DanielAmsel** [comment]
Yeah I did, but as the RNA-seq part was left out in this pipeline, I think this issue is not related to the pipeline anymore and therefore could be closed.

**Comment by greatfireball** [comment]
Agree! Therefore, I will close the issue
