### ISSUE TITLE
Outputfiles

### ISSUE THREAD

**Issue by DanielAmsel** [microPIECE-team/microPIECE#47]
#### mature miRNA set

mature_combined_mirbase_novel.fa := 
mature microRNA set, containing novels and miRBase-completed (if mined), together with the known miRNAs from miRBase

#### precursor miRNA set

hairpin_combined_mirbase_novel.fa := 
precursor microRNA set, containing novels (if mined), together with the known miRNAs from miRBase

#### mature miRNA expression per condition

miRNA_expression.csv := 
Semicolon-separated file : rpm;condition;miRNA

#### miRDeep2 mining result in HTML

result_02_03_2018_t_09_30_01.html:= 
the standard output HTML file of miRDeep2

#### all library support-level target predictions

*_miranda_output.txt :=
miranda output, reduced to the lines, starting with > only

#### all library support-level CLIP transfer .bed files

*transfered_merged.bed := 
bed-file of the transferred CLIP-regions in speciesB transcriptome

**Comment by greatfireball** [comment]
Added csv to miRDeep2 mining result in `README.md` and `microPIECE.pl`

**Comment by greatfireball** [comment]
Description was included into README.md and source code, therefore the issue will be closed.

Thanks for the description @DanielAmsel
