### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by greatfireball** [microPIECE-team/microPIECE#90]
I think we should add a CONTRIBUTING.md to clarify the requirements to contribute to the microPIECE.

Again, we might adopt the [CONTRIBUTING.md](https://github.com/chloroExtractorTeam/chloroExtractor/blob/master/CONTRIBUTING.md) from the chloroExtractor project.

Opinions  @DanielAmsel ?

Would include #89

**Comment by DanielAmsel** [comment]
agree
